### ISSUE TITLE
Import of package on iOS crashes

### ISSUE THREAD

**Issue by Rutger** [Volst/react-native-honeywell-scanner#1]
`index.js` uses `HoneywellScanner` as an object. However, on iOS this variable will be undefined and it crashes: `undefined is not an object (evaluating 'HoneywellScanner.BARCODE_READ_SUCCESS')`

We  probably shouldn't make an `/ios/`-folder, but we should fix this by changing `index.js`.

This could be "fixed" by replacing
```
const HoneywellScanner = NativeModules.HoneywellScanner;
```
to 
```
const HoneywellScanner = NativeModules.HoneywellScanner || {};
```
, but that's not very clean either.

**Comment by SpaceK33z** [comment]
Fixed in 1.0.1
