### ISSUE TITLE
Link command not update build.gradle file

### ISSUE THREAD

**Issue by duytq94** [Volst/react-native-honeywell-scanner#3]
Hi, that's a great lib, thanks.
But just notice that seem link command not work perfectly 100%, it's missing
`dependencies {
    compile project(':react-native-honeywell-scanner')
}`
at app\build.gradle. You should add manually guide link for checking when link command not work.

**Comment by SpaceK33z** [comment]
I've just released version 2.0 with support for RN 0.60 so this should no longer be an issue, let me know if it still is.
