### ISSUE TITLE
Pause honeywel scanner

### ISSUE THREAD

**Issue by amansahil** [Volst/react-native-honeywell-scanner#5]
When moving to another screen with the Honeywell scanner listener I want to pause the Honeywell scanner listener of the previous screen.

I pass the onStart & onStop as props to the next screen and call it there but it does not do the job, I think it's because the 'barcodeReadFail' event needs to be triggered natively and I'm not sure how to do that

```

   const handleScan = useCallback(event => {
        setBarcode(event)
        onScan && onScan(event)
    }, [onScan])

    const stopScan = () => {
        console.log('The scanner has been stopped')
    }

 const onStart = () => {
        HoneywellScanner.on('barcodeReadSuccess', handleScan) 
 }

 const onStop = () => {        
        HoneywellScanner.off('barcodeReadFail', stopScan)
 }
```

**Comment by SpaceK33z** [comment]
Do you call `HoneywellScanner.stopReader()` to stop listening? If you are using react-navigation, do note that the component doesn't unmount when you move to another screen. Instead you'll need to listen to when the focus of the screen is lost, [see docs](https://reactnavigation.org/docs/en/function-after-focusing-screen.html).

**Comment by amansahil** [comment]
Hey, @SpaceK33z, that’s what I’m doing now, but an option to pause an instance of the scanner and start it again would be neat.
