### ISSUE TITLE
DataCollection.jar

### ISSUE THREAD

**Issue by aliismayilov** [Volst/react-native-honeywell-scanner#6]
What's the purpose of https://github.com/Volst/react-native-honeywell-scanner/blob/4cf48c38a120b950fca80af86506773eb645acc2/android/libs/DataCollection.jar

can't really find any reference to it?

**Comment by SpaceK33z** [comment]
This contains the Honeywell SDK, without it you can't access the scanner. I got it from here somewhere; https://www.honeywellaidc.com/products/software/developer-library .

**Comment by aliismayilov** [comment]
I see. Thank you!
