### ISSUE TITLE
cannot use library

### ISSUE THREAD

**Issue by hhdivil** [Volst/react-native-honeywell-scanner#8]
Hi I am getting the following error

ExceptionsManager.js:74 TypeError: _reactNativeHoneywellScanner.default.startReader is not a function

This error is located at:
    in App (at withExpoRoot.js:20)
    in RootErrorBoundary (at withExpoRoot.js:19)
    in ExpoRootComponent (at renderApplication.js:35)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:98)
    in RCTView (at View.js:45)
    in View (at AppContainer.js:115)
    in AppContainer (at renderApplication.js:34)

My code:

import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import HoneywellScanner from 'react-native-honeywell-scanner';
export default function App() {
    HoneywellScanner.startReader().then((claimed) => {
        console.log(claimed ? 'Barcode reader is claimed' : 'Barcode reader is busy');
    });
    return (
        <View style={styles.container}>
            <Text>Open up App.js to start working on your app!</Text>
        </View>
    );
}

const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
    },
});

Am I doing something wrong?  If I do `console.log(HoneywellScanner);` I get `{on: ƒ, off: ƒ}` so the library must be getting included

Thank you!
Dave

**Comment by hhdivil** [comment]
If I use `console.log(HoneywellScanner.isCompatible);` it is undefined

**Comment by asimalali** [comment]
@hhdivil Have you found any solution ?
